### PR TITLE
Fix main and rename mobile form 2

### PR DESCRIPTION
**Pull request by gbirke**

### CODE REVIEW

**Review by moiikana — APPROVED** [review]

**Comment by moiikana** [comment]
I think you have to do the renaming from the second commit in the archived banners as well. When we restore them we would want them to work with our current components.

**Review by moiikana — CHANGES_REQUESTED** [review]
probably necessary to also change the imports of `begyearlyrecurringdonationformstep2mobile` in the archive, that way we could restore an archived banner easier with our current components

**Comment by gbirke** [comment]
I have split the main fix into #1132 so I can do the rename thing properly, whithout descending into rebase hell

**Comment by gbirke** [comment]
I've split this and have a new PR #1134 which addresses your comment

**Pull request closed without merging**
